management:
  endpoint:
    gateway:
      enabled: true
    endpoints:
      web:
        exposure:
          include: gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
              - AuthFilter
        - id: fortunes-service
          uri: lb://FORTUNES-SERVICE
          predicates:
            - Path=/fortune/**
          filters:
              - AuthFilter
        - id: friends-service-persons
          uri: lb://FRIENDS-SERVICE
          predicates:
            - Path=/persons/**
          filters:
              - AuthFilter
        - id: friends-service-posts
          uri: lb://FRIENDS-SERVICE
          predicates:
            - Path=/posts/**
          filters:
              - AuthFilter
        - id: chat-service-rest
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-utils/**
          filters:
            - AuthFilter
        - id: chat-service-websocket
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/ws/**
